-- 0013_sop_engine
--
-- The SOP execution engine. Three new tables (sop_run, sop_step_state,
-- sop_deliverable) wrap the existing scanners and turn raw findings into
-- assignable, validated, deliverable work — the structural fix that
-- converts the dashboard from a reporting tool into an execution tool
-- per the Steve Toth AEO Coaching SOP catalog (24 SOPs across 7 phases).
--
-- See docs/design-sop-engine.md for the full design.
--
-- Also: extend remediation_ticket with the prescription-layer fields it
-- was missing — title, description, priority_rank, remediation_copy,
-- validation_steps, evidence_links — plus an FK to sop_run so each
-- ticket carries provenance back to the SOP step that generated it.

-- ───────────────────────────────────────────────────────────────
-- sop_run — one row per (firm × SOP instance)
-- ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "sop_run" (
  "id"                       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "firm_id"                  uuid NOT NULL REFERENCES "firm"("id") ON DELETE CASCADE,
  "sop_key"                  text NOT NULL,
  "phase"                    integer NOT NULL,
  "status"                   text NOT NULL DEFAULT 'not_started',
  "current_step"             integer NOT NULL DEFAULT 1,
  "started_at"               timestamptz,
  "completed_at"             timestamptz,
  "paused_at"                timestamptz,
  "next_review_at"           timestamptz,
  "depends_on_sop_run_id"    uuid REFERENCES "sop_run"("id") ON DELETE SET NULL,
  "meta"                     jsonb NOT NULL DEFAULT '{}'::jsonb,
  "created_by"               text NOT NULL DEFAULT 'system',
  "created_at"               timestamptz NOT NULL DEFAULT now()
);

-- Most common query: "all SOP runs for firm X, grouped by phase, latest
-- status" — index supports the Phase grid on /dashboard/[firmSlug]/sops.
CREATE INDEX IF NOT EXISTS "sop_run_firm_phase_idx"
  ON "sop_run" ("firm_id", "phase", "status");

-- Second query: "what's the latest run for sop_key X on firm Y" —
-- supports the dependency check and the cadence follow-up cron.
CREATE INDEX IF NOT EXISTS "sop_run_firm_sop_idx"
  ON "sop_run" ("firm_id", "sop_key", "created_at" DESC);

-- Follow-up scheduler cron query: "completed runs whose next_review_at
-- is now in the past and don't yet have a successor."
CREATE INDEX IF NOT EXISTS "sop_run_review_due_idx"
  ON "sop_run" ("next_review_at")
  WHERE "next_review_at" IS NOT NULL AND "status" = 'completed';

-- ───────────────────────────────────────────────────────────────
-- sop_step_state — one row per (sop_run × step)
-- ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "sop_step_state" (
  "id"                       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "sop_run_id"               uuid NOT NULL REFERENCES "sop_run"("id") ON DELETE CASCADE,
  "step_number"              integer NOT NULL,
  "step_key"                 text NOT NULL,
  "status"                   text NOT NULL DEFAULT 'not_started',
  "started_at"               timestamptz,
  "completed_at"             timestamptz,
  "operator_confirmations"   jsonb NOT NULL DEFAULT '[]'::jsonb,
  "output_summary"           jsonb NOT NULL DEFAULT '{}'::jsonb,
  "notes"                    text
);

-- Each step number is unique per run — enforced so completeStep() can
-- ON CONFLICT update rather than insert duplicates.
CREATE UNIQUE INDEX IF NOT EXISTS "sop_step_state_run_step_uniq"
  ON "sop_step_state" ("sop_run_id", "step_number");

-- ───────────────────────────────────────────────────────────────
-- sop_deliverable — terminal artifacts a SOP produces
-- ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "sop_deliverable" (
  "id"             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "sop_run_id"     uuid NOT NULL REFERENCES "sop_run"("id") ON DELETE CASCADE,
  "kind"           text NOT NULL,
  "name"           text NOT NULL,
  "payload"        jsonb NOT NULL DEFAULT '{}'::jsonb,
  "blob_url"       text,
  "generated_at"   timestamptz NOT NULL DEFAULT now()
);

-- Deliverable list per run is short (typically 1-3); a simple FK index
-- is enough.
CREATE INDEX IF NOT EXISTS "sop_deliverable_run_idx"
  ON "sop_deliverable" ("sop_run_id", "generated_at" DESC);

-- ───────────────────────────────────────────────────────────────
-- remediation_ticket — extend with prescription-layer fields
-- ───────────────────────────────────────────────────────────────
-- These are all nullable so existing rows stay valid. New tickets
-- generated by SOP step factories populate them; the legacy auto-
-- generated tickets that already exist for Andrew Pickett Law / other
-- firms keep their current shape until the data migration script
-- backfills them.

ALTER TABLE "remediation_ticket"
  ADD COLUMN IF NOT EXISTS "sop_run_id"      uuid REFERENCES "sop_run"("id") ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS "sop_step_number" integer,
  ADD COLUMN IF NOT EXISTS "title"           text,
  ADD COLUMN IF NOT EXISTS "description"     text,
  ADD COLUMN IF NOT EXISTS "priority_rank"   integer,
  ADD COLUMN IF NOT EXISTS "remediation_copy" text,
  ADD COLUMN IF NOT EXISTS "validation_steps" jsonb,
  ADD COLUMN IF NOT EXISTS "evidence_links"   jsonb;

-- Action-items page query: "all tickets for firm X, grouped by SOP
-- run, sorted by priority_rank within each group" — supports the
-- renamed /dashboard/[firmSlug]/action-items surface.
CREATE INDEX IF NOT EXISTS "remediation_ticket_sop_idx"
  ON "remediation_ticket" ("firm_id", "sop_run_id", "priority_rank");
